// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47ICFUDjR7U5mlJcUhR9QAm3VBdy8kyQ',
    appId: '1:972752217378:web:7ede022ad210421db0b17b',
    messagingSenderId: '972752217378',
    projectId: 'servtol-3405d',
    authDomain: 'servtol-3405d.firebaseapp.com',
    storageBucket: 'servtol-3405d.appspot.com',
    measurementId: 'G-DGKP349FJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMXqh4FwNUYAaxXTXVHhreEK91GsDqJQ',
    appId: '1:972752217378:android:b3f7dceeb8b77661b0b17b',
    messagingSenderId: '972752217378',
    projectId: 'servtol-3405d',
    storageBucket: 'servtol-3405d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6SSV2_8uY6cOoy6KQfD_JGZG9ZemD-Uo',
    appId: '1:972752217378:ios:9819f9b3a73fec51b0b17b',
    messagingSenderId: '972752217378',
    projectId: 'servtol-3405d',
    storageBucket: 'servtol-3405d.appspot.com',
    iosBundleId: 'com.example.servtol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6SSV2_8uY6cOoy6KQfD_JGZG9ZemD-Uo',
    appId: '1:972752217378:ios:41efc4105d28b625b0b17b',
    messagingSenderId: '972752217378',
    projectId: 'servtol-3405d',
    storageBucket: 'servtol-3405d.appspot.com',
    iosBundleId: 'com.example.servtol.RunnerTests',
  );
}
